### ISSUE TITLE
resources as np-bennys required np-fml

### ISSUE THREAD

**Issue by paramboy** [Adoggman/NoPixelServer#1]
resources as np-bennys reference a script in np-fml/server/lib.lua and is missing
something in that bennys  resources is working but i cant figure out what becouse for enable the menu i had to insert in the db a business and i couldnt do that in game (not realy familiar with the server), the script want in DB "tuner_carshop" in order to activate it (if u have done it ill be very happy if there is some documentation or something to do for tryng that resources, it sees is something like whitelisted job but is different)
problem is np-fml, bennys is not the only one referncing that lib

**Comment by paramboy** [comment]
i was digging in to the files, it seems bennys resource point to "character_passes" tab in to the db, infact the column inside are id,cid,rank,name,giver,pass_type,business_name,bank
where business_name need to be "tuner_carshop" in order to work
i think there is an automation in the server for populate that tab but i could't find it
alsoin the admin pannel all this jobs dosent show 

inside resource isPed client.lua
local BusinessNames = {
	["gym"] = "LS Gym",
	["golf"] = "Golf Course",
	["strip_club"] = "Vanilla Unicorn",
	["illegal_carshop"] = "Camel Tows",
	["winery_factory"] = "Delmar & Caine",
	["carpet_factory"] = "Carpet Company",
	["life_invader"] = "Life Invader",
	["casino"] = "Los Santos Casino",
	["real_estate"] = "Los Santos Real Estate",
	["weed_factory"] = "The Greenery",
	["chop_shop"] = "Choppers",
	["parts_shop"] = "Parts Shop",
	["recycle_shop"] = "Recycle Centre",
	["car_shop"] = "Car Shop",
	["repairs_harmony"] = "Harmony Repairs",
	['tuner_carshop'] = "Tuner Carshop",
	['dock_worker'] = "Dock Worker",
	['lost_mc'] = "The Lost MC",
	['ug_racing'] = "Underground Racing",
	['hoa'] = "Home Owners Assoc.",
        ['rooster_academy'] = "The Rooster Academy",
        ['sahara_int'] = "Sahara International",
        ['drift_school'] = "Overboost Drift",

**Comment by Aniket999969** [comment]
how to use np-eblips any idea?

**Comment by paramboy** [comment]
> how to use np-eblips any idea?

Aniket, i dont want be rude, its like your fifth comment on this eblips, we will issue that when times come to fix it, server is not ready as Adoggman already answerd you.
He is working on file server and you will know when its ready when he releses a stable version of it.
i'm here because i want to help this project and im tryng to understund how systems work.
If you want to be helpful open a issue tread and post "np-eblips not working"
when times comes someone will figure out and fix it, np-eblips is not the only think is not working here
