### ISSUE TITLE
/outfits commands doesn't work

### ISSUE THREAD

**Issue by gtaroleplayer** [Adoggman/NoPixelServer#10]
When I go to the apartments and get next to the wardrobe i type /outfitadd 1 Casual and nothing happens

**Comment by Alex0989** [comment]
> When I go to the apartments and get next to the wardrobe i type /outfitadd 1 Casual and nothing happens

u can use /outfits command in cloth shops and all change cloth area with "Press M To Change"

**Comment by JajarGaming** [comment]
> > When I go to the apartments and get next to the wardrobe i type /outfitadd 1 Casual and nothing happens
> 
> u can use /outfits command in cloth shops and all change cloth area with "Press M To Change"

I think you are right, but you can create outfits only at the clothe shops or at PD ; Hospital

**Comment by gtaroleplayer** [comment]
> > When I go to the apartments and get next to the wardrobe i type /outfitadd 1 Casual and nothing happens
> 
> u can use /outfits command in cloth shops and all change cloth area with "Press M To Change"

Well it might work in those places but I should be able to change my outfits in my apartment too

**Comment by Adoggman** [comment]
Fix pulled from @AnasHamrouni
