### ISSUE TITLE
Police Radio Limit Range

### ISSUE THREAD

**Issue by Alex0989** [Adoggman/NoPixelServer#14]
police radio have very close range (np-voice range) and limit - radio voice disable for distance

**Comment by Adoggman** [comment]
Can you explain further in depth what you think should be happening and what is happening?

**Comment by gtaroleplayer** [comment]
Does the radio even works? When i buy and use one nothing happens

**Comment by Adoggman** [comment]
Did you set the frequency?

**Comment by gtaroleplayer** [comment]
> Did you set the frequency?

when i drag the radio to USE doesnt do anything at all, doesnt spawn the radio png, nothing

**Comment by Alex0989** [comment]
> > Did you set the frequency?
> 
> when i drag the radio to USE doesnt do anything at all, doesnt spawn the radio png, nothing

if u have radio in your inventory press Shift + p for use radio

**Comment by Alex0989** [comment]
> Can you explain further in depth what you think should be happening and what is happening?

me and friend set in police we have 2 radio - we set frequents and when we stand each other (in car and close area) we press caps log for transmit and we hear voice in radio but if we go far distant (not so far this is very close range) if press caps log to talk just we hear radio beep and we cant hear voice
