### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by EloMonarch** [Adoggman/NoPixelServer#2]
Hi, I am sorry for the (possibly) dumb question, but I am having problems on installing. I have cloned the files but I don't seem to find out where I am supposed to put the files. I have created a fivem server at this folder: "C:\Users\PC\Desktop\server1\ctx-server-data" (server.cfg) file is here while the server start is at "C:\Users\PC\Desktop\server1". When I created the server I also got a "txData" file on my desktop. I tried coppying the files from your repository to the location where the server start is, but it keeps closing when I try to start it. Then I also tried deleting all the files in there and just put yours, but I keep getting a " x file is missing" error. I could really use some help if possible.

**Comment by h04X-2K** [comment]
download the newest fxserver on https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/ i use 3753

**Comment by EloMonarch** [comment]
> download the newest fxserver on https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/ i use 3753

then delete everything in the folder that has FXServer.exe and copy the repository in there?

**Comment by h04X-2K** [comment]
I did it this way 

![tempsnip](https://user-images.githubusercontent.com/42872111/113586860-5691f480-962e-11eb-9e88-56ac8d6fa0d9.png)

**Comment by EloMonarch** [comment]
does the "database user/password" refer to phpMyAdmin?

**Comment by EloMonarch** [comment]
I get this error when I try to set-password: "FINDSTR: Cannot open C:\Users\PC\Desktop\server2\\.git\config"
is there a way to manually change it? I put the wrong things on DB info and now I can't change it to normal.

**Comment by h04X-2K** [comment]
You don't need the bat

**Comment by EloMonarch** [comment]
> You don't need the bat

So, how can I change my DB info? I've put the wrong username - password for it and it cant access it when I launch the server

**Comment by paramboy** [comment]
Yes you can, in the main folder there Is a hidden folder called .Git, inside there Is a file called "config" modify It with notepad

**Comment by EloMonarch** [comment]
> Yes you can, in the main folder there Is a hidden folder called .Git, inside there Is a file called "config" modify It with notepad

Oh thanks, but that was not the case for me, I went into ghmattimysql > config.json and change it through there

**Comment by EloMonarch** [comment]
In the Admin Menu under "commands" there is nothing, shouldn't I be able to spawn vehicles and do other stuff too through there?

**Comment by h04X-2K** [comment]
Start the server create a char and than go in the DB under user group set dev or owner thats it

**Comment by Adoggman** [comment]
> > Yes you can, in the main folder there Is a hidden folder called .Git, inside there Is a file called "config" modify It with notepad
> 
> Oh thanks, but that was not the case for me, I went into ghmattimysql > config.json and change it through there

Yep, this where the DB access is configured. I'll add this info to the readme.
