### ISSUE TITLE
np-scoreboard not actually fixed and doorlock problem

### ISSUE THREAD

**Issue by JajarGaming** [Adoggman/NoPixelServer#24]
I know the scoreboard is by default not started but I've started it as it looks good and that's the only way to check your ID without opening your phone.

I haven't noticed any visual bugs except from the "Recent Disconnects" not showing up for me

[Bug](https://gyazo.com/c6a919194d53b243c071f2d883254ee7)
----------------------------------------------------------------------------------------------------------------------------------------------
When you are in the area of MRPD the doorlock text will appear, but it seems like its coming from pillbox hospital.

[Bug](https://gyazo.com/3bcfbe829f8d3782c259e9728a3c16e6)

**Comment by Adoggman** [comment]
Not going to bother with scoreboard for a while myself, other issue I will look into at some point.
