### ISSUE TITLE
disconnected by server: fetching steamid

### ISSUE THREAD

**Issue by francismilton** [Adoggman/NoPixelServer#27]
Is it just me? Every time I try to log in it appears this error about fetching steamid, I dont know if it is related to the database or not but I just camt seem to find the fix for it.

**Comment by Alex0989** [comment]
> Is it just me? Every time I try to log in it appears this error about fetching steamid, I dont know if it is related to the database or not but I just camt seem to find the fix for it.

your steam must be open

**Comment by francismilton** [comment]
> > Is it just me? Every time I try to log in it appears this error about fetching steamid, I dont know if it is related to the database or not but I just camt seem to find the fix for it.
> 
> your steam must be open

it is xd

**Comment by francismilton** [comment]
Im trying to clone again, might be because of wrong cloning folder.

**Comment by h04X-2K** [comment]
guys you need a steam web Api Key

**Comment by francismilton** [comment]
Yes I used it also but the thing is first time I did it correct but I
couldnt access database acc and the next try I skipped the steamweb api and
I could login to my db acc so its just some error on my part probably

A quarta, 7/04/2021, 14:08, h04X ***@***.***> escreveu:

**Comment by francismilton** [comment]
im gonna close this post for now and see if it works, if not I shall address it later on.

**Comment by francismilton** [comment]
[image: image.png]
[image: image.png]

Hey, sry for the inconvenience but now that I fixed that last problem I
have this thing, I think its still related to steam but I used correct
steamwebapi, steamID and fivem key aswell so, only if its related to my db.
I tried to remove some errors from db tho, like putting some default null
values on columns that had errors and those tables didnt get created at the
beginning so I did that and then I rollback to default sql file, so its
still the same original nopixel.sql. Idk man if u can help dm me and thanks
