### ISSUE TITLE
Police tazer dont work

### ISSUE THREAD

**Issue by AndreasFromDanmark** [Adoggman/NoPixelServer#29]
The police tazer can not shot, i dont no if there is a keybind to turn off a "gun safety" or it missing armor?

**Comment by Alex0989** [comment]
> The police tazer can not shot, i dont no if there is a keybind to turn off a "gun safety" or it missing armor?

we have tazer ammo (tazer battery charge) item, in inventory item lists - but i added tazer ammo idk why not work i change fivem build and result: 

in default fivem build tazer not work
in 2060 build tazer work with reload animation (without tazer ammo)
in 2189 build tazer work with out reload animation (without tazer ammo)
