### ISSUE TITLE
PDM mutiple issues  also ranks issue

### ISSUE THREAD

**Issue by EliasMatta** [Adoggman/NoPixelServer#30]
When i want to buy regular vehicles like job vehicles and bikes i cant and i have lots of money in cash and bank also the rank system for working at PDM not working and i am rank 5  i cant finance cars dunno if there is a command  to finance i forgot also i cant replace cars in showroom

**Comment by Dankbudbaker** [comment]
Set your rank with character passes to pdm then you can change the car that you want and to finance you stand near the car and type /finance then the finance option will pop up next to buy. But the buy is broken. I can only finance.

**Comment by EliasMatta** [comment]
is the PDM job in the database is the  car_shop
