### ISSUE TITLE
Some resources have an outdated resource manifest

### ISSUE THREAD

**Issue by AndreasFromDanmark** [Adoggman/NoPixelServer#32]
what fivem artifacts is this server working 100% on? I just put it on build 3796

[ citizen-server-impl] Some resources have an outdated resource manifest:
[ citizen-server-impl]     - InteractSound
[ citizen-server-impl]     - LockDoors
[ citizen-server-impl]     - banking
[ citizen-server-impl]     - baseevents
[ citizen-server-impl]     - boatshop
[ citizen-server-impl]     - carwash
[ citizen-server-impl]     - chat
[ citizen-server-impl]     - coordsaver
[ citizen-server-impl]     - es_taxi
[ citizen-server-impl]     - jobsystem
[ citizen-server-impl]     - koil-debug
[ citizen-server-impl]     - koilWeatherSync
[ citizen-server-impl]     - lmfao
[ citizen-server-impl]     - lux_vehcontrol
[ citizen-server-impl]     - medicgarage
[ citizen-server-impl]     - minimap
[ citizen-server-impl]     - np-actionbar
[ citizen-server-impl]     - np-barriers
[ citizen-server-impl]     - np-camera
[ citizen-server-impl]     - np-contracts
[ citizen-server-impl]     - np-dealer
[ citizen-server-impl]     - np-dirtymoney
[ citizen-server-impl]     - np-fish
[ citizen-server-impl]     - np-furniture
[ citizen-server-impl]     - np-gurgle
[ citizen-server-impl]     - np-gym
[ citizen-server-impl]     - np-heatmap
[ citizen-server-impl]     - np-jewelrob
[ citizen-server-impl]     - np-news
[ citizen-server-impl]     - np-notepad
[ citizen-server-impl]     - np-oBinoculars
[ citizen-server-impl]     - np-oHideFrames
[ citizen-server-impl]     - np-oPlayerNumbers
[ citizen-server-impl]     - np-oRecoil
[ citizen-server-impl]     - np-oStress
[ citizen-server-impl]     - np-restart
[ citizen-server-impl]     - np-secondaryjobs
[ citizen-server-impl]     - np-stripperbitches
[ citizen-server-impl]     - np-taskbar
[ citizen-server-impl]     - np-taskbarskill
[ citizen-server-impl]     - np-taskbarthreat
[ citizen-server-impl]     - np-tasknotify
[ citizen-server-impl]     - np-taximeter
[ citizen-server-impl]     - np-tow
[ citizen-server-impl]     - np-tuner
[ citizen-server-impl]     - np-votesystem
[ citizen-server-impl]     - np-warrants
[ citizen-server-impl]     - np-webpages
[ citizen-server-impl]     - pNotify
[ citizen-server-impl]     - sessionmanager
[ citizen-server-impl]     - tf-pointing
[ citizen-server-impl]     - veh

**Comment by JajarGaming** [comment]
I suggest using 3060 because it works the best with everything. And in 3060 you have a taser reload animation.

**Comment by AndreasFromDanmark** [comment]
@JajarGaming 3060? you dont mean 2060?

**Comment by JajarGaming** [comment]
> @JajarGaming 3060? you dont mean 2060?

I meant 2060
