### ISSUE TITLE
Blip on player and spawn menu help

### ISSUE THREAD

**Issue by evilstriker** [Adoggman/NoPixelServer#4]
-How do I remove the red blip that's stuck on the player? Picture: https://prnt.sc/1156mhz

-Where can I edit the spawn menu? Picture: https://prnt.sc/1156o19

-And when is the calling feature being fixed with the phone?

Thanks in advance!

**Comment by Adoggman** [comment]
> -How do I remove the red blip that's stuck on the player? Picture: https://prnt.sc/1156mhz
Don't know, working on it now.

> -Where can I edit the spawn menu? Picture: https://prnt.sc/1156o19
Don't know.

> -And when is the calling feature being fixed with the phone?
I haven't even started looking at the phone.

**Comment by Aniket999969** [comment]
Okay so i founder the fix for e-blips its occuring due to e-blips

**Comment by Adoggman** [comment]
> Okay so i founder the fix for e-blips its occuring due to e-blips

Any other information? I'm assuming you removed eblips and it went away?

**Comment by M1ke0G** [comment]
From what I've seen I believe he is referencing a "Destination" blip.
